# About the technology

This version of the book uses the *R* [^R] programming language to
implement resampling algorithms.

The authors of the R language wrote it specifically for data analysis and statistics.  If you are used to other programming languages, R won't be very hard to get used to.  If you are new to programming, there are many features in R that make it relatively easy to do many of the tasks we need for this book, such as loading data from files, manipulating sequence of data values, and doing plots.

## The environment {-}

For each chapter that has code, there is an matching *R Notebook*
[^r-notebook].  In the web edition of this book, you can click on the
*Download* link at the top of the page to download the chapter as a notebook.

In the print version of the book, we point you to the web version, to get the links.

## Running the code on your own computer {-}

It is reasonably easy to set up your own computer so you can run the code in this book.

First install the R language by going the download section of R website
[^R-lang], downloading the installer for your computer, and running the
installer.

Next go to the *R Studio* website [^rstudio].  Follow the links to the
download section, then download and install the *RStudio desktop*.  Choose the
free version unless you have a reason not to.

Now open the RStudio application and open the notebook that you downloaded
from the website.  You should now be able to run the code from the chapter on
your own computer, and experiment by making changes.
