# Variables to fill _quarto.yml and _variables.yml files.
# This file filled recursively, so variables fully defined here
# can also be format-filled into this same file.
# edition, version, other-version filled from dictionary initializing read.
url-root: "https://resampling-stats.github.io"
book-url-root: "{url-root}/{edition}-{version}"
edition: {edition}
version: {version}
other-version: {other-version}
interact-sdir: interact
r:
  filter_divspans: "['python']"
  nb_flatten_divspans: "['+', 'r']"
  nb_format: 'Rmd'
  kernel_name: 'webR'
  kernel_display: '"R (webR)"'
  url_data_root: "/{interact-sdir}/files/data"
python:
  filter_divspans: "['r']"
  nb_flatten_divspans: "['+', 'python']"
  nb_format: 'ipynb'
  kernel_name: 'python'
  kernel_display: '"Python (Pyodide)"'
  url_data_root: "null"
