---
resampling_with:
    ed2_fname: null
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.14.6
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Coding with resampling

This book covers the basics of coding in {{< var lang >}}, as a tool for
resampling.   We use resampling, in turn, as a tool for understanding
probability and statistics.  As you have seen, the same tool can serve to
design and run statistical tests.

This appendix chapter gathers together links to the text in the book that
covers coding in {{< var lang >}}.  It is a reference when you want to remind
yourself of a particular aspect of {{< var lang >}}.

* Comments after lines of code: @nte-eol-comments.
* Types of values in {{< var lang >}}: @sec-types-values.
[  * Lists: @sec-lists.]{.python}
[  * Arrays: @sec-arrays.]{.python}
* Strings — values containing text: @sec-intro-to-strings.
* Selecting multiple elements from {{< var array >}}s with {{< var array >}}s
  with slicing: @sec-slice-indexing.
* `for` loops: @sec-for-loops.\
[* Modules and submodules: @nte-modules-submodules.]{.python}
* bincount / tabulate (probability_theory_2_compound).
* (a == 1) & (b == 3) (in `more_sampling_tools`)
* Python `range` cf `np.arange` (`resampling_with_code`)
* `np.all` (done in `probabality_theory_4_finite`).
* Plotting and histograms (and histogram bins and bin edges): @sec-on-histograms.
  `probability_theory_3`), covering plotting, bins, bin edges.  We might
  consider a chapter on histograms.
* Underscores in Python integers by `testing_counts_1` (done in
  `testing_counts_1`).
* `seq` / `np.arange` with floats done in `testing_counts_1`.
* Building strings with [`paste`]{.r}[format-strings]{.python}:
  @sec-building-strings.
*  Logical operators — *or*[ (`|`)]{.r}, *and*[ (`&`)]{.r}: @sec-logical-operators.
* `if` statements:  @sec-if-statements.
* The *absolute* function ([`np.abs`]{.python}[`abs`]{.r}): @nte-abs-function.
* Squaring values and {{< var array >}}s: @sec-squared-arrays.
* Concatenating {{< var array >}}s: @sec-concatenate.
