---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.14.5
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Standard deviation and standard scores

```{python}
from pathlib import Path

import numpy as np
import pandas as pd
pd.set_option('mode.copy_on_write', True)
from textwrap import wrap

data_path = Path('data')
```

```{python}
df = pd.read_csv(data_path / 'premier_league_2021.csv')
points_wages = df[['team', 'points', 'wages_year']].rename(
    columns={'wages_year': 'wages'})
points_wages
```

```{r}
df <- read.csv('data/premier_league_2021.csv')
df
```
```{r}
points <- df$points
points
```

```{r}
wages <- df$wages_year
wages
```


```{python}
points = points_wages['points']
wages = points_wages['wages']
point_str = ', '.join(str(p) for p in points)
py_prefix = 'points = np.array(['
py_points = '\n'.join(wrap(f"{py_prefix}{point_str}])", 70,
                      subsequent_indent=' ' * len(py_prefix)))
r_prefix = 'points <- c('
r_points = '\n'.join(wrap(f'{r_prefix}{point_str})', 70,
                      subsequent_indent=' ' * len(r_prefix)))
print(f"""\
```{{python}}
{py_points}
```

```{{r}}
{r_points}
```
""")
```

```{python}

```
