---
jupyter:
  jupytext:
    metadata_filter:
      notebook:
        additional: all
        excluded:
        - language_info
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.6
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
resampling_with:
    ed2_fname: Technical
---

# Technical Note to the Professional Reader

The material presented in this book fits together with the technical
literature as follows: Though I (JLS) had proceeded from first principles
rather than from the literature, I have from the start cited work by Chung and
Fraser [-@chung1958randomization] and Meyer Dwass [-@dwass1957modified] They
suggested taking samples of permutations in a two-sample test as a way of
extending the applicability of Fisher's randomization test
[-@fisher1935design; -@fisher1960design, chapter III, section 21]. Resampling
with replacement from a single sample to determine sample statistic
variability was suggested by Simon [-@simon1969basic]. Independent work by
Efron [-@efron1979bootstrap] explored the properties of this technique (Efron
termed it the "bootstrap") and lent it theoretical support. The notion of
using these techniques routinely and in preference to conventional techniques
based on Gaussian assumptions was suggested by Simon [-@simon1969basic] and by
Simon, Atkinson, and Shevokas [-@simon1976probability].
